version: '2'

services:
  server:
    build: ./docker/ruby
    image: bxl/mooris-ruby:2.4.1
    container_name: bxl_mooris_ruby
    volumes_from:
      - code
    ports:
      - 3000
      - 8808
    links:
      - code
    tty: true

  code:
    build: ./docker/volume
    image: bxl/volume
    container_name: bxl_mooris_ruby_volume
    volumes:
    - ./srv:/srv
    environment:
      SETUP_VOLUME: "/srv"