version: '2'

services:
  server:
    build: ./docker/ruby
    image: bxl/sdk-ruby:2.5
    container_name: bxl_sdk_ruby
    volumes_from:
      - code
    ports:
      - 3000
      - 8808
    links:
      - code
    tty: true

  code:
    build: ./docker/volume
    image: bxl/volume
    container_name: bxl_sdk_ruby_volume
    volumes:
    - ./srv:/srv
    environment:
      SETUP_VOLUME: "/srv"